CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name TEXT,
    surname TEXT,
    email TEXT,
    age TEXT,
    description TEXT
);

SET @counter = 0;

INSERT INTO users (name, surname, email, age, description)
SELECT
    SUBSTRING(MD5(RAND()) FROM 1 FOR 8) AS name,
    SUBSTRING(MD5(RAND()) FROM 1 FOR 8) AS surname,
    CONCAT('user', @counter := @counter + 1, '@example.com') AS email,
    FLOOR(RAND() * 100) AS age,
    CONCAT('Description for user ', @counter) AS description
FROM
    (
        SELECT 1 AS n UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL
        SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL
        SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL
        SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL
        SELECT 13 UNION ALL SELECT 14 UNION ALL SELECT 15 UNION ALL
        SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL
        SELECT 19 UNION ALL SELECT 20 UNION ALL SELECT 21 UNION ALL
        SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL
        SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL
        SELECT 28 UNION ALL SELECT 29 UNION ALL SELECT 30
    ) numbers;
    